DATA 40000,"viliam >imko",30000,"martina >imkov=",20000,"ivan perinaj",10000,"martin perinaj",5000,"palko kincel",3000,"du>a buocov=",2000,"imro drgo@",1000,"martin kviatkovsk~",500,"toma> jech",100,"Devil"
DATA GSTART,FLATER,CVIATE,NALAVO,TUNAKK,VYASAM,UJOAJE,JOZOMA,AHOJTY,VEDJEA,SOMONA,STUDNA,TRAVIA,TERCIA,PRETOT,VALACH

MERGE "colortrans.bas"
MERGE "create.destroy.bas"
MERGE "destabil.bas"
MERGE "devilinfo.bas"
MERGE "door.bas"
MERGE "effect.bas"
MERGE "fall.bas"
MERGE "final.bas"
MERGE "font.bas"
MERGE "gameerror.bas"
MERGE "gameloop.bas"
MERGE "gamestatus.bas"
MERGE "getswgfx.bas"
MERGE "ghost.bas"
MERGE "go.left.bas"
MERGE "go.right.bas"
MERGE "go.wall.bas"
MERGE "hof.bas"
MERGE "hpn.bas"
MERGE "initgame.bas"
MERGE "inpbufclr.bas"
MERGE "joystick.bas"
MERGE "jump.bas"
MERGE "jump.wall.bas"
MERGE "laser.bas"
MERGE "laser.old.bas"
MERGE "makebox.bas"
MERGE "newlevel.bas"
MERGE "nothing.bas"
MERGE "options.bas"
MERGE "pick.bas"
MERGE "pkill.bas"
MERGE "prginfo.bas"
MERGE "sadd.bas"
MERGE "scrnext.bas"
MERGE "setstyle.bas"
MERGE "startmenu.bas"
MERGE "sword.left.bas"
MERGE "sword.right.bas"
MERGE "teleport.bas"
MERGE "testxy.bas"
MERGE "turn.left.bas"
MERGE "turn.right.bas"
MERGE "vystrek.bas"
MERGE "waitforinput.bas"
MERGE "win.bas"
MERGE "winner.bas"

initgame
gameloop

